In [3]:
split_path = "/nfs/users/ext_shikhar.srivastava/workspace/MedicalTaskonomy/data/CT/splits/balanced/raw"
split_path += '/fetal_ultrasound_train.json'

In [4]:
import torch
import os 
import numpy as np
import json
dt_split_file = open(split_path, mode="r")
_dataset_data = json.load(dt_split_file)

In [9]:
for k,v in _dataset_data.items():
    print(k,len(v))

inputs 9883
classes 9883
masks 0
studies 9883


In [11]:
import pandas as pd
_dataset_data = pd.DataFrame(dict([ (k,pd.Series(v)) for k,v in _dataset_data.items() ]))

/tmp/ipykernel_1458/888300359.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  _dataset_data = pd.DataFrame(dict([ (k,pd.Series(v)) for k,v in _dataset_data.items() ]))


In [15]:
_dataset_data

inputs  classes  masks       studies
0     Patient01450_Plane1_9_of_14_0.pt        0    NaN  Patient01450
1      Patient01013_Plane2_1_of_1_0.pt        0    NaN  Patient01013
2     Patient00720_Plane1_6_of_27_0.pt        0    NaN  Patient00720
3     Patient00873_Plane1_1_of_23_0.pt        0    NaN  Patient00873
4     Patient01408_Plane1_5_of_15_0.pt        0    NaN  Patient01408
...                                ...      ...    ...           ...
9878  Patient01551_Plane1_7_of_22_0.pt        0    NaN  Patient01551
9879   Patient01120_Plane2_1_of_1_0.pt        0    NaN  Patient01120
9880   Patient01100_Plane4_1_of_1_0.pt        0    NaN  Patient01100
9881  Patient00832_Plane1_7_of_21_0.pt        0    NaN  Patient00832
9882   Patient01200_Plane1_2_of_2_0.pt        0    NaN  Patient01200

[9883 rows x 4 columns]

In [16]:
_dataset_data = _dataset_data.sample(frac=0.8, random_state=123)
dataset_data = _dataset_data.reset_index(drop=True).to_dict(orient='list')

In [4]:
import torch
import os 
import numpy as np
path = '/nfs/projects/mbzuai/shikhar/datasets/ofa/our_data_path/meta_train.pt'
data = torch.load(path)

In [5]:
model_zoo = torch.load('/nfs/projects/mbzuai/shikhar/datasets/ofa/our_mod_zoo.pt')

In [9]:
import pandas as pd

df = pd.DataFrame(model_zoo)

In [11]:
df[df['dataset'] == 'MosMed']

best_epoch        f1      loss  \
167         100  0.768421  0.074524   
204          49  0.806202  0.170831   
205          32  0.703252  0.430663   
213          15  0.764286  0.126464   
214          15  0.749153  0.488681   
225           7  0.756184  0.476181   
226          46  0.698152  0.382845   
228          62  0.788155  0.397998   
240           5  0.752080  0.462442   
241          13  0.697417  0.228970   
247          86  0.741866  0.106506   
256          16  0.805243  0.161028   
257          15  0.731707  0.494106   
258          20  0.718404  0.498016   
265          88  0.738337  0.324455   
278          90  0.686981  0.048811   
287          57  0.855172  0.386515   
350          57  0.671642  0.270405   
352           6  0.722222  0.513598   
355          75  0.648188  0.521066   
362          97  0.765784  0.089883   
371          11  0.857143  0.332358   
373          88  0.739726  0.279356   
378          39  0.721831  0.700929   
404          23  0.609037  0.482625   
405          23  0.745234  0.444698   
406          22  0.649299  0.482125   
410          95  0.663636  0.215940   
414          81  0.777311  0.222815   
435          67  0.842795  0.052824   
438          29  0.617234  0.368462   
443          24  0.731183  0.442245   
448          46  0.712000  0.407327   
467          46  0.678112  0.466303   
471          44  0.702703  0.143112   

                                            model_path dataset  \
167  /nfs/projects/mbzuai/BioMedIA/MICCIA_22/logs/c...  MosMed   
204  /nfs/projects/mbzuai/BioMedIA/MICCIA_22/logs/c...  MosMed   
205  /nfs/projects/mbzuai/BioMedIA/MICCIA_22/logs/c...  MosMed   
213  /nfs/projects/mbzuai/BioMedIA/MICCIA_22/logs/c...  MosMed   
214  /nfs/projects/mbzuai/BioMedIA/MICCIA_22/logs/c...  MosMed   
225  /nfs/projects/mbzuai/BioMedIA/MICCIA_22/logs/c...  MosMed   
226  /nfs/projects/mbzuai/BioMedIA/MICCIA_22/logs/c...  MosMed   
228  /nfs/projects/mbzuai/BioMedIA/MICCIA_22/logs/c...  MosMed   
240  /nfs/projects/mbzuai/BioMedIA/MICCIA_22/logs/c...  MosMed   
241  /nfs/projects/mbzuai/BioMedIA/MICCIA_22/logs/c...  MosMed   
247  /nfs/projects/mbzuai/BioMedIA/MICCIA_22/logs/c...  MosMed   
256  /nfs/projects/mbzuai/BioMedIA/MICCIA_22/logs/c...  MosMed   
257  /nfs/projects/mbzuai/BioMedIA/MICCIA_22/logs/c...  MosMed   
258  /nfs/projects/mbzuai/BioMedIA/MICCIA_22/logs/c...  MosMed   
265  /nfs/projects/mbzuai/BioMedIA/MICCIA_22/logs/c...  MosMed   
278  /nfs/projects/mbzuai/BioMedIA/MICCIA_22/logs/c...  MosMed   
287  /nfs/projects/mbzuai/BioMedIA/MICCIA_22/logs/c...  MosMed   
350  /nfs/projects/mbzuai/BioMedIA/MICCIA_22/logs/c...  MosMed   
352  /nfs/projects/mbzuai/BioMedIA/MICCIA_22/logs/c...  MosMed   
355  /nfs/projects/mbzuai/BioMedIA/MICCIA_22/logs/c...  MosMed   
362  /nfs/projects/mbzuai/BioMedIA/MICCIA_22/logs/c...  MosMed   
371  /nfs/projects/mbzuai/BioMedIA/MICCIA_22/logs/c...  MosMed   
373  /nfs/projects/mbzuai/BioMedIA/MICCIA_22/logs/c...  MosMed   
378  /nfs/projects/mbzuai/BioMedIA/MICCIA_22/logs/c...  MosMed   
404  /nfs/projects/mbzuai/BioMedIA/MICCIA_22/logs/c...  MosMed   
405  /nfs/projects/mbzuai/BioMedIA/MICCIA_22/logs/c...  MosMed   
406  /nfs/projects/mbzuai/BioMedIA/MICCIA_22/logs/c...  MosMed   
410  /nfs/projects/mbzuai/BioMedIA/MICCIA_22/logs/c...  MosMed   
414  /nfs/projects/mbzuai/BioMedIA/MICCIA_22/logs/c...  MosMed   
435  /nfs/projects/mbzuai/BioMedIA/MICCIA_22/logs/c...  MosMed   
438  /nfs/projects/mbzuai/BioMedIA/MICCIA_22/logs/c...  MosMed   
443  /nfs/projects/mbzuai/BioMedIA/MICCIA_22/logs/c...  MosMed   
448  /nfs/projects/mbzuai/BioMedIA/MICCIA_22/logs/c...  MosMed   
467  /nfs/projects/mbzuai/BioMedIA/MICCIA_22/logs/c...  MosMed   
471  /nfs/projects/mbzuai/BioMedIA/MICCIA_22/logs/c...  MosMed   

               model  with_aug  balanced  pretrained  batch_128   topn  \
167     mobilenet_v2      True      True       False       True  top-7   
204  efficientnet_b4      True     False       False      False  top-7   
2

In [108]:
import torch
import os
import numpy as np
def torch_load(fpath):
    return torch.load(fpath, map_location=torch.device('cpu'))

load_path = '/nfs/users/ext_shikhar.srivastava/workspace/TANS/outcomes/ours/20220527_1037/retrieval/retrieval.pt'

cross_modal_info = torch.load(load_path, map_location=torch.device('cpu'))
datasets_cross_modal_info = np.array(cross_modal_info['dataset'])

In [109]:
np.arange(19)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])

In [110]:
# array of random values between 0 and 1 such with shape datasets_cross_modal_info.shape[0]
random_values = np.random.rand(datasets_cross_modal_info.shape[0]) 


In [111]:
random_values

array([6.63607854e-01, 3.55470420e-01, 1.61681044e-01, 6.13709698e-02,
       4.73196197e-01, 2.94618446e-01, 4.65498673e-01, 2.10251925e-01,
       6.55130093e-01, 6.73326084e-01, 3.42025771e-02, 8.92894262e-01,
       5.73702787e-01, 5.56877926e-01, 2.41798781e-01, 8.20813752e-01,
       6.46296502e-02, 9.09284608e-01, 9.54494842e-01, 6.37998736e-01,
       9.69918384e-01, 9.53841734e-01, 5.66706478e-01, 2.07386467e-01,
       5.84896621e-01, 6.95071953e-01, 9.43944660e-01, 8.87186949e-01,
       1.30045875e-01, 3.16446577e-01, 9.24414814e-01, 4.86215335e-01,
       8.46966131e-01, 9.65625034e-01, 7.47248583e-01, 4.24217924e-01,
       1.99821277e-02, 8.91632530e-01, 1.85307800e-03, 2.69188243e-01,
       6.61501049e-01, 1.43772999e-01, 4.89602328e-01, 5.29517786e-02,
       2.54503834e-01, 9.56855328e-01, 8.60762161e-01, 8.78709573e-01,
       5.08411221e-01, 8.64542617e-02, 7.28529989e-01, 8.90894312e-01,
       9.82425014e-01, 6.74412426e-01, 5.24387381e-01, 5.99570812e-02,
      

In [112]:
rand_idx

tensor([ 12,  16, 417])

In [113]:
len(cross_modal_info['dataset'])

476

In [114]:
cross_modal_info.keys()

dict_keys(['dataset', 'm_emb', 'f1', 'best_epoch', 'loss', 'model_path', 'model', 'with_aug', 'balanced', 'pretrained', 'batch_128', 'topn'])

In [115]:
import json
# Load a text file
def load(filename):
    """Read json txt file"""
    with open(filename) as json_file:
        data = json.load(json_file)
    return data

In [116]:
brain_mri = load('/nfs/users/ext_shikhar.srivastava/workspace/TANS/outcomes/ours/20220527_1037/20220529_0759/logs/Brain_MRI.txt')

In [117]:
# for all files in path, open and print the file name
path = '/nfs/users/ext_shikhar.srivastava/workspace/TANS/outcomes/ours/20220527_1037/20220529_0759/logs'
import os
for file in os.listdir(path):
    print(file)
    f = load(path+'/'+file)
    print(f['results']['retrieval'].keys())

ImageCHD.txt
dict_keys(['search_time', '0', '2', '8'])
ProstateMRI.txt
dict_keys(['search_time', '0', '8'])
CTPancreas.txt
dict_keys(['search_time', '0', '7', '8'])
LiTs.txt
dict_keys(['search_time', '0', '6', '1'])
fetal_ultrasound.txt
dict_keys(['search_time', '0', '1'])
RSNAXRay.txt
dict_keys(['search_time', '0', '9'])
IHD_Brain.txt
dict_keys(['search_time', '0', '7', '8'])
Brain_MRI.txt
dict_keys(['search_time', '0', '6', '1'])
Covid19XRay.txt
dict_keys(['search_time', '0', '7', '8'])
kits.txt
dict_keys(['search_time', '0', '3', '7'])
MosMed.txt
dict_keys(['search_time', '0', '4', '6'])
RSPECT.txt
dict_keys(['search_time', '0', '8', '9'])


In [118]:
brain_mri['results']['retrieval']['0']['info']

{'task': 'ProstateMRI',
 'model': 'efficientnet_b4',
 'with_aug': True,
 'balanced': False,
 'pretrained': False,
 'batch_128': True,
 'topn': 'raw',
 'best_epoch': 47,
 'path': '/nfs/projects/mbzuai/BioMedIA/MICCIA_22/logs/classification/CT/post_sanity/raw/Feb23_19-18-51_p4-r66-b.g42cloud.net_classify_raw_efficientnetb4_ProstateMRI_batch_128_with_weights_with_shuffle_with_aug/model_epoch_47.pt'}

In [119]:
brain_mri['results']['retrieval']['0']['scores'].keys()

dict_keys(['pre_train_f1', 'ep_lss', 'ep_acc', 'f1', 'f1_hat', 'ep_tr_time', 'ep_te_time'])

In [120]:
brain_mri['results']['retrieval']['0']['scores']['ep_acc']

[0.535483870967742,
 0.4935483870967742,
 0.5193548387096775,
 0.5919354838709677,
 0.5483870967741935,
 0.5919354838709677,
 0.5854838709677419,
 0.5967741935483871,
 0.646774193548387,
 0.6451612903225806,
 0.6532258064516129,
 0.6887096774193548,
 0.75,
 0.6403225806451613,
 0.6645161290322581,
 0.7129032258064517,
 0.7338709677419355,
 0.7564516129032258,
 0.6548387096774193,
 0.7677419354838709,
 0.7274193548387097,
 0.7419354838709677,
 0.7290322580645161,
 0.7354838709677418,
 0.7290322580645161,
 0.7741935483870968,
 0.764516129032258,
 0.7483870967741936,
 0.7451612903225806,
 0.7870967741935485,
 0.8145161290322581,
 0.7596774193548386,
 0.7177419354838711,
 0.7887096774193548,
 0.7483870967741936,
 0.7887096774193548,
 0.7709677419354839,
 0.8274193548387098,
 0.8112903225806452,
 0.7725806451612903,
 0.7806451612903226,
 0.7467741935483871,
 0.8129032258064516,
 0.7903225806451614,
 0.7967741935483871,
 0.8387096774193549,
 0.8483870967741935,
 0.8306451612903226,
 0.856451

In [121]:
brain_mri['results']['retrieval']

{'search_time': 0.0030972957611083984,
 '0': {'scores': {'pre_train_f1': 0.3016129032258065,
   'ep_lss': [1.0236791703008836,
    1.1207166771734915,
    1.1635972234510605,
    0.8889604137789818,
    1.0056456981166717,
    0.922322371698195,
    0.9870688922943608,
    0.9216103069243893,
    0.8325284769458156,
    0.7670065510657526,
    0.8241845388566295,
    0.7401638388633728,
    0.6596993004122088,
    0.7690109600943904,
    0.7568419679518669,
    0.7078336954116822,
    0.6452565150876199,
    0.632665692990826,
    0.9065134748335808,
    0.6037913034039158,
    0.6830767843031114,
    0.6846640079252182,
    0.7119716140531724,
    0.7332899735819909,
    0.6469809514860954,
    0.5889182433005302,
    0.6432159125804902,
    0.7013790947775687,
    0.6829484789602218,
    0.6301185315655123,
    0.5166154284631053,
    0.6239034668091805,
    0.737657622368105,
    0.5638963268649193,
    0.6313852279416976,
    0.5746703032524355,
    0.6294210845424283,
    0.493295

In [122]:
import pandas as pd
pd.DataFrame(file)

ValueError: DataFrame constructor not properly called!